# Generated by Django 4.2.1 on 2023-05-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_logo',
            field=models.FileField(upload_to='org_logo'),
        ),
    ]
