# Generated by Django 4.2.1 on 2023-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_organisation_org_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
