# Generated by Django 4.2.1 on 2023-05-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_customuser_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_pic'),
        ),
    ]
